# Generated by Django 2.2.4 on 2021-03-04 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20210303_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_amigo', models.CharField(max_length=20)),
                ('agregados', models.ManyToManyField(related_name='agregados', to='login_app.User')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador', to='login_app.User')),
            ],
        ),
    ]
